### ISSUE TITLE
error:non-JRMP server at remote endpoint

### ISSUE THREAD

**Issue by mysqlplus** [toomanyopenfiles/jmxmon#3]
2017-03-20 16:01:57,241 [main] INFO  [com.stephan.tof.jmxmon.Config] - init config
2017-03-20 16:01:57,370 [main] INFO  [com.stephan.tof.jmxmon.Config] - /usr/local/falcon-agent/jmxmon/./jmxmon.jvm.context.json is not exist
2017-03-20 16:01:57,370 [main] INFO  [com.stephan.tof.jmxmon.Config] - init config ok
2017-03-20 16:01:58,262 [pool-1-thread-1] ERROR [com.stephan.tof.jmxmon.JMXMonitor] - non-JRMP server at remote endpoint
java.rmi.ConnectIOException: non-JRMP server at remote endpoint
        at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:248)
        at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
        at sun.rmi.server.UnicastRef.newCall(UnicastRef.java:342)
        at sun.rmi.registry.RegistryImpl_Stub.lookup(Unknown Source)
        at com.stephan.tof.jmxmon.jmxutil.ProxyClient.checkSslConfig(ProxyClient.java:274)
        at com.stephan.tof.jmxmon.jmxutil.ProxyClient.<init>(ProxyClient.java:167)
        at com.stephan.tof.jmxmon.jmxutil.ProxyClient.getProxyClient(ProxyClient.java:518)
        at com.stephan.tof.jmxmon.JMXMonitor.runTask(JMXMonitor.java:58)
        at com.stephan.tof.jmxmon.JMXMonitor.access$0(JMXMonitor.java:50)
        at com.stephan.tof.jmxmon.JMXMonitor$1.run(JMXMonitor.java:41)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

这大概什么原因？

**Comment by msadu** [comment]
正常，需要监控的端口没开启jmx监控，开启就行了

**Comment by ILOVEQIUXIAOYI** [comment]
> 正常，需要监控的端口没开启jmx监控，开启就行了

这个是需要java去开启，还是监控插件进行配置？应该怎么开启jmx监控？

**Comment by HwiLu** [comment]
我也遇到了这个问题。我的是namenode的jmx，肯定是开启了jmx监控的，还是报这个错，有大佬解决了么。
`# netstat -anp | grep 50070`

`tcp        0      0 10.22.1.9:50070      0.0.0.0:*               LISTEN      31627/java`

**Comment by moyouxuan000000** [comment]
#

> 我也遇到了这个问题。我的是namenode的jmx，确定是开启了jmx监控的，还是报这个错误，有大佬解决了么。 `# netstat -anp | grep 50070`
> 
> `tcp 0 0 10.22.1.9:50070 0.0.0.0:* LISTEN 31627/java`

同问，我也是这样，解决了吗您

**Comment by HwiLu** [comment]
> 

都忘记了，已经离职了

**Comment by HwiLu** [comment]
> > 我也遇到了这个问题。我的是namenode的jmx，确定是开启了jmx监控的，还是报这个错误，有大佬解决了么。 `# netstat -anp | grep 50070`
> > `tcp 0 0 10.22.1.9:50070 0.0.0.0:* LISTEN 31627/java`
> 
> 同问，我也是这样，解决了吗您

都忘记了，已经离职了
